package com.example.demo.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder    // LOMBOCK will generated appropriated source code for builder !!!
@Data
@AllArgsConstructor
@NoArgsConstructor
/**
 * Cette classe illustre une classe et son builder construit par LOMBOCK AUTOMATIQUEMENT
 * grace à l'annotation "@Builder". C'est nettement moins verbeux et évite les erreurs
 * de ré-écriture des attributs !
 */
public class EtudiantPrenomNomDto {
    private String nom;
    private String prenom;

/**
 *  The builder source code will be generated by LOMBOCK at compilation !
 */
}
