package com.example.demo.expandlombock;



public class EtudiantPrenomNomDto {
    private String nom;
    private String prenom;

    public EtudiantPrenomNomDto(String nom, String prenom) {
        this.prenom=prenom;
        this.nom=nom;
    }
    public EtudiantPrenomNomDto() {}
    public String getNom() { return this.nom; }
    public String getPrenom() { return this.prenom;   }

    /**
     * builder generated by Lombock
     *
     */

    // STATIC method generate an intermediate class EtudiantPrenomNomDtoBuilder
    public static EtudiantPrenomNomDtoBuilder builder() {
        return new EtudiantPrenomNomDtoBuilder(); }

    // STATIC class used to
    public static class EtudiantPrenomNomDtoBuilder {
        private String nom;
        private String prenom;

        public EtudiantPrenomNomDtoBuilder nom(String nom) { this.nom = nom; return this; }
        public EtudiantPrenomNomDtoBuilder prenom(String prenom) { this.prenom = prenom; return this; }

        public EtudiantPrenomNomDto build() {
            return new EtudiantPrenomNomDto(this.nom, this.prenom); }

        public String toString() {
            return "EtudiantPrenomNomDto.EtudiantPrenomNomDtoBuilder(nom=" + this.nom + ", prenom=" + this.prenom + ")"; } }

    public void setNom(String nom) { this.nom = nom; }
    public void setPrenom(String prenom) { this.prenom = prenom; }



}

